
services:
  rtdetr-api:
    build:
      context: ./inference
      dockerfile: Dockerfile
    image: rtdetr-api:latest
    container_name: rtdetr-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    gpus:
      - device_ids: ["1"]
        capabilities: ["gpu"]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      ENGINE_PATH: /app/models/rtdetr-l.engine
      NVIDIA_VISIBLE_DEVICES: "1"          # fallback for older runtimes
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    restart: unless-stopped
    networks:
      - ai-net            

  vnc-instance-1:
    image: ai-sandbox
    build:
      context: ./agent          # <- folder that contains the Dockerfile you pasted
      dockerfile: Dockerfile
    container_name: vnc-instance-1
    ports:
      - "5901:5901"
    volumes:
      - ./tasks:/tasks:rw
      # Mount host Firefox Snap profile and cache into container
      - /home/theiss/snap/firefox/common/.mozilla:/root/.mozilla:rw
      - /home/theiss/snap/firefox/common/.cache/mozilla:/root/.cache/mozilla:rw
    gpus:
      - device_ids: ["0"]
        capabilities: ["gpu"]
    environment:
      AGENT_MODE: dynamic
      RTDETR_API_URL: "http://rtdetr-api:8000/predict"   # <-- key line
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      TASK_PLANNER_URL: http://task-planner:8000/v1/actions/next
      PLANNER_API_KEY: taskPlannerApiSecret
      # Explicitly set Firefox binary and profile (adjust profile dir name if different)
      FIREFOX_BIN: "/usr/bin/firefox-esr"
      FIREFOX_PROFILE_PATH: "/root/.mozilla/firefox/agent1.default-esr"
      AGENT_GOAL: "Wait for Gmail to login and get to Inbox.  Once in inbox... Continually do the following: Compose emails to andrew.theiss@gmail.com and mention that his AI is working.  Send the email.  If not on the Compose Email Page, go back to Inbox.  Repeat 5 times.  Go to sent mail and verify the message was sent each time."
      SECRETS_EMAIL: "abc@example.com"
      SECRETS_PASSWORD: "correcthorsebatterystaple"
    restart: unless-stopped
    depends_on:
      - rtdetr-api
      - task-planner
    networks:
      - ai-net

  vnc-instance-2:
    image: ai-sandbox
    container_name: vnc-instance-2
    ports:
      - "5902:5901"
    volumes:
      - ./tasks:/tasks:rw
      - ./profiles/agent-2/.mozilla:/root/.mozilla:rw
      - ./profiles/agent-2/.cache/mozilla:/root/.cache/mozilla:rw
    gpus:
      - device_ids: ["0"]
        capabilities: ["gpu"]
    environment:
      AGENT_MODE: dynamic
      RTDETR_API_URL: "http://rtdetr-api:8000/predict"   # <-- key line
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      TASK_PLANNER_URL: http://task-planner:8000/v1/actions/next
      PLANNER_API_KEY: taskPlannerApiSecret
      FIREFOX_BIN: "/usr/bin/firefox-esr"
      FIREFOX_PROFILE_PATH: "/root/.mozilla/firefox/agent2.default-esr"
      AGENT_GOAL: "Login to mail.com with user: ${SECRETS_EMAIL}, pass: ${SECRETS_PASSWORD}, then wait for Inbox"
      SECRETS_EMAIL: "abc@example.com"
      SECRETS_PASSWORD: "correcthorsebatterystaple"
    restart: unless-stopped
    depends_on:
      - rtdetr-api
      - task-planner
    networks:
      - ai-net

  task-planner:
    build:
      context: ./taskPlanner
      dockerfile: Dockerfile
    container_name: task-planner
    ports:
      - "8010:8000"
    environment:
      PLANNER_API_KEY: taskPlannerApiSecret
      OLLAMA_OPENAI_BASE: http://host.docker.internal:11434/v1
      OLLAMA_MODEL: gpt-oss:120b
    # map host.docker.internal on Linux (Desktop already provides it)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-net

networks:
  ai-net:
    driver: bridge

volumes:
  agent1_mozilla:
  agent1_cache:
  agent2_mozilla:
  agent2_cache: